# Generated by Django 3.1 on 2020-08-07 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restauracja', models.CharField(max_length=100)),
                ('czasdodania', models.DateTimeField(auto_now_add=True)),
                ('zamowienione_danie', models.TextField(blank=True)),
                ('data_losowania', models.DateTimeField(blank=True, null=True)),
                ('losowanie_odbyte', models.BooleanField(default=False)),
                ('wygrany', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
