# Generated by Django 3.1 on 2020-08-18 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milosowisko_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='czasdodania',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='zamowienione_danie',
        ),
        migrations.CreateModel(
            name='ZamowioneDanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czasdodania', models.DateTimeField(auto_now_add=True)),
                ('zamowienione_danie', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='zamowienian',
            field=models.ManyToManyField(to='milosowisko_app.ZamowioneDanie'),
        ),
    ]
