# Generated by Django 3.1 on 2020-08-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milosowisko_app', '0002_auto_20200818_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='wygrany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
